### ISSUE TITLE
 That's what we want too... thanks

### ISSUE THREAD

**Issue by bitores** [samdauwe/BabylonCpp#1]
Supported Compilers
MSVC >= 2017 (YES!)

Supported Operating Systems
Windows >= 7 (YES!)

But..
now the project compilation seems to have reported a lot of errors

Added, 
this project is very, very good

**Comment by samdauwe** [comment]
Thanks for the nice feedback. On your request I will give the Windows support a higher priority. Get back to me in a week then I know what needs to be done to get this working on Windows.

**Comment by bitores** [comment]
I see you have a lot of updates about the MSVC compiler.
Look forward to seeing can run this babyloncpp project in Win 7

**Comment by samdauwe** [comment]
Yes, supporting the MSVC compiler has my full attention now. You will see more updates in the next days. Still many issues left to resolve.

**Comment by bitores** [comment]
Cool, can now be used to develop win 2017 what?

**Comment by bitores** [comment]
![image](https://user-images.githubusercontent.com/17512181/30624301-2fb43688-9def-11e7-8e51-db05870eafcf.png)


Cool, can now be used to develop win 2017 what?

**Comment by samdauwe** [comment]
I made good progress in resolving the errors for Visual Studio 2017. For the moment I am working to get the materials library, extensions and samples compile on Windows. I am hoping to have the examples working by Sunday.

On Windows you can create the Visual Studio solution file with the command:
python cmake_build.py configure

This will create the file BabylonCpp.sln in the release_build folder that you can open in Visual Studio. Expect a lot of compiler warnings.

Any interest in contributing to this project once the samples are working on Windows? There is still a lot of work to do and Babylon.js is growing really fast. It is a lot of work for one person. You could help with testing, creating examples and made code contributions to the core library. What do you think?

**Comment by bitores** [comment]
If you can start, I want to create a community to pull a gang to participate in this excellent project

**Comment by bitores** [comment]
If I can start, I want to create a community to pull a gang to participate in this excellent project.

**Comment by samdauwe** [comment]
Thanks! Any help is welcome. Let's hope that this works on Windows in a few days so you can start playing with it and can have an idea of the current state. Then we can further discuss the top priorities.

**Comment by samdauwe** [comment]
Visual Studio 2017 is now officially supported and AppVeyor builds are automatically running.

It is recommended to run de builds in 'debug mode' on Windows for now because the samples are not fully stable yet.
