### ISSUE TITLE
First time VS 2017 compiling

### ISSUE THREAD

**Issue by japerator** [samdauwe/BabylonCpp#12]
Hi there,
I stumbled across your babylon port. I can't  seem to get it it compile for VS. Any advice at what would cause that? Keep up the good work.
[CMakeError.log](https://github.com/samdauwe/BabylonCpp/files/2545483/CMakeError.log)
[CMakeOutput.log](https://github.com/samdauwe/BabylonCpp/files/2545484/CMakeOutput.log)

**Comment by samdauwe** [comment]
Hello japerator!

Thanks for your message!

In the file _CMakeError.log_ I see the line:
> cl : Command line warning D9002: ignoring unknown option '-std=c++17'

The logs indicate you are using compiler version 19.13.26132, my compiler version is 19.15.26732.1. Beside the difference in compiler version I don't see anything different compared to my config. So, according to me, you will need to upgrade your Visual Studio 2017 to a more recent version (i.e. latest Visual Studio 2017 update version 15.8.9) that has better C++17 support. 

On Visual Studio 2017 update version 15.8.9 I see a failing C++17 check (as shown on the last line in the log below) on my side, but the compilation process succeeds.

> C:\Users\Sam\Documents\GitHub\BabylonCpp>python cmake_build.py configure
> Executing command '['cmake', '../', '-DCMAKE_BUILD_TYPE=Release', '-G', 'Visual Studio 15 2017 Win64']' in directory 'release_build'
> -- The C compiler identification is MSVC 19.15.26732.1
> -- The CXX compiler identification is MSVC 19.15.26732.1
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PythonInterp: C:/Program Files/Python27/python.exe (found suitable version "2.7.9", minimum required is "2.7.0")
> -- Found OpenGL: opengl32
> -- Performing Test COMPILER_SUPPORTS_CXX17
> -- Performing Test COMPILER_SUPPORTS_CXX17 - Failed

In case the Visual Studio 2017 version upgrade did not resolve the issue, then we can try some other things :)

Best regards,
Sam

**Comment by japerator** [comment]
Thanks for the response. I thought I was running latest. I can ensure you I am now. Unfortunately, I get the same error. Time for some other things ;)
[CMakeError.log](https://github.com/samdauwe/BabylonCpp/files/2546378/CMakeError.log)

**Comment by samdauwe** [comment]
Hi japerator,

oh, so no luck with updating the Visual Studio 2017 version.

Next step we can try is to figure out if this is an issue in your environment or if there is an issue in the cmake configuration.

Can you try if you can build another cmake projects, like [GLFW](https://github.com/glfw/glfw)?
Or are you also getting the error on other projects.

If this works, you could try doing a new checkout of the BablonCpp repo (to have a clean setup) and doing the build manually, by launching the developer command prompt for visual studio:

> mkdir build
> cd build
> cmake.exe -DCMAKE_BUILD_TYPE=Release -G 'Visual Studio 15 2017 Win64' ../

If the cmake command succeeds, you should see a solution file that can be opened in Visual Studio. You can use the IDE for doing the build instead of the build script.

Best regards,
Sam

**Comment by samdauwe** [comment]
Tested on fresh windows installation but cannot reproduce the issue. AppVeyor builds are succeeding too. Seems to be a configuration / environment settings issue on your machine.

Best regards,
Sam
