### ISSUE TITLE
Roadmap / Checklist

### ISSUE THREAD

**Issue by fmmoret** [samdauwe/BabylonCpp#13]
Hey -- curious if you have an internal roadmap or checklist you're working off of. It'd be nice to surface it somewhere on here; I think it'd empower other people on Github to start helping you out.

**Comment by samdauwe** [comment]
Hello fmmoret,

yes I just recently started an internal roadmap on [this wiki page](https://github.com/samdauwe/BabylonCpp/wiki/Roadmap), but it is on monthly basis.

I am working on getting the code in sync with the last release v3.3.0 and debugging features through examples. If you can motivate people to provide some help (or feedback) or defining some priorities that can attract more people that would be very welcome :) My personal roadmap is getting the Sponza demo scene working by end of January, there are still some things to do like debugging bones support; particles, fix scene loading issues. I can define some tasks here if needed.

Thanks,
Sam
