### ISSUE TITLE
Error when compiling in linux

### ISSUE THREAD

**Issue by JesusAlexlara** [samdauwe/BabylonCpp#3]
when I compile the project I get an error in the file "babylon/core/nullable.h" with the message error: ‘BABYLON::Nullable<T>::_value’ has incomplete type
   T _value;

I can not find the solution Thank you

**Comment by samdauwe** [comment]
Should be resolved now (some includes were missing). I am currently working on getting the examples working again due to all the changes for BabylonJS 3.2.0. The ShaderMaterial examples are working now but the other ones need further investigation. I will keep you update on my progress.
