### ISSUE TITLE
Run in Vs2017 Debug- x64 Failed!

### ISSUE THREAD

**Issue by marshal-it** [samdauwe/BabylonCpp#72]
clone finished, and build finished, no error. but i dont know how to start up.

![image](https://user-images.githubusercontent.com/3109971/72591762-f1c08080-393b-11ea-91f8-910330a773ac.png)

![image](https://user-images.githubusercontent.com/3109971/72591832-292f2d00-393c-11ea-8963-b11c4a69f0ee.png)

**Comment by samdauwe** [comment]
Hello,

Thanks for trying out BaylonCpp!

By default, the startup project is not properly set. When you set the startup project to _BabylonStudio_ as illustrated in the screenshot below, does the studio launches on your end?

![msvc_babylon_studio_startup_project](https://user-images.githubusercontent.com/24841018/72639437-dff3d300-3965-11ea-8767-d6357b9abe63.png)

Note: there were a lot of code changes in the past week, so not all examples are working. We are currently working on resolving the issues.

Best regards,
Sam

**Comment by marshal-it** [comment]
Build Successful. But I run BabyIonSudio with [Debug x64], issue error!  
![image](https://user-images.githubusercontent.com/3109971/72677450-92977300-3ad7-11ea-8e90-ee3087466d7b.png)
![image](https://user-images.githubusercontent.com/3109971/72677461-ae9b1480-3ad7-11ea-8ae6-37c093619cef.png)
![image](https://user-images.githubusercontent.com/3109971/72677484-dd18ef80-3ad7-11ea-8a15-78f1600477dc.png)

**Comment by samdauwe** [comment]
Hello,

yes, the _glClearDepthf_ given an error on Windows but not on other platforms.

Could you pull the latest code? The _glClearDepthf_ call has been replaced by _glClearDepth_ with [this commit](https://github.com/samdauwe/BabylonCpp/commit/5e7aac8d96a8a3e96a93047042bd5c3eaad78d84).

Once the BabylonStudio app started you should should see an empty scene and then you can choose examples in the example browser.

Thanks,
Sam

**Comment by marshal-it** [comment]
I pull the latest core, no error and run well.
Thanks, good project.

**Comment by marshal-it** [comment]
New Issue. 
![image](https://user-images.githubusercontent.com/3109971/72722838-4e30d380-3bba-11ea-9ebd-699b623fcb29.png)

![image](https://user-images.githubusercontent.com/3109971/72722877-66085780-3bba-11ea-81ac-be0545c1fa72.png)

**Comment by marshal-it** [comment]
New Issue. PbrMaterial Run No 3D Scene.
![image](https://user-images.githubusercontent.com/3109971/72723838-ae287980-3bbc-11ea-9916-13e689752f76.png)

**Comment by samdauwe** [comment]
Thanks for the issue reports!

There is an issue with some examples related to asynchronous loading of assets. I will get back to you later this week when I have a solution for those issues.

Best regards,
Sam

**Comment by samdauwe** [comment]
Hello,

for now I can refer to a [more stable branch](https://github.com/pthom/BabylonCpp/tree/stable) from Nov 22nd when most of the examples were working. This version should give a better experience with the library compared to the master branch.

Best regards,
Sam

**Comment by samdauwe** [comment]
Hello,

the file loading issues have been resolved in the master branch. So I can close this issue now.

Best regards,
Sam
