### ISSUE TITLE
applyEffectWrapper

### ISSUE THREAD

**Issue by marshal-it** [samdauwe/BabylonCpp#82]
hdr_filtering.obj : error LNK2019: unresolved external symbol "public: void __cdecl BABYLON::EffectRenderer::applyEffectWrapper(class std::shared_ptr<class BABYLON::EffectWrapper> const &)" (?applyEffectWrapper@EffectRenderer@BABYLON@@QEAAXAEBV?$shared_ptr@VEffectWrapper@BABYLON@@@std@@@Z) referenced in function "private: class std::shared_ptr<class BABYLON::BaseTexture> __cdecl BABYLON::HDRFiltering::_prefilterInternal(class std::shared_ptr<class BABYLON::BaseTexture> const &)" (?_prefilterInternal@HDRFiltering@BABYLON@@AEAA?AV?$shared_ptr@VBaseTexture@BABYLON@@@std@@AEBV34@@Z)

![image](https://user-images.githubusercontent.com/3109971/85394257-e4f62780-b580-11ea-91f8-5f8904c20943.png)
![image](https://user-images.githubusercontent.com/3109971/85394307-f3dcda00-b580-11ea-896a-f4c46da4e3d6.png)

**Comment by samdauwe** [comment]
@marshal-it Thanks for letting me know!

I fixed the error and resolved some of the warnings reported by the MSVC compiler. Could you pull the latest code to check if the issue is resolved now on your side?

Best regards,
Sam
