### ISSUE TITLE
Cant draw text on DynamicTexture because FramebufferCanvas::getContext2d() returns nullptr

### ISSUE THREAD

**Issue by swinefeaster** [samdauwe/BabylonCpp#88]
i'm trying to do this but get a crash. is there a workaround? thanks!

        DynamicTextureOptions textureOptions{};
        textureOptions.width = 60;
        textureOptions.height = 60;
        textureOptions.canvas = _canvas;

        auto dynamicTexture = DynamicTexture::New("DynamicTexture", textureOptions, _scene, true /*generateMipMaps*/);
        dynamicTexture->hasAlpha = true;
        dynamicTexture->drawText("some text", 5, 40, "bold 36px Arial", "white", "transparent", true /*invertY*/);

**Comment by samdauwe** [comment]
Hi,

Dynamic textures are not yet fully supported, and the function drawText is provided but not implemented... In BabylonJS the HTML canvas API is used for drawing text when using the dynamic texture. For BabylonCpp I needed an C++ alternative for the canvas API but I could not find a good one, however, using the [Sokol headers](https://github.com/floooh/sokol) this could be achieved but needs some integration work.

Is this issue a blocking factor for you, for trying out the library ?

Thanks and best regards

**Comment by swinefeaster** [comment]
Thanks for the quick response. I have thought of a few workarounds, such as not having any text whatsoever in the canvas 🤣.

Sent with 🍄
________________________________

**Comment by samdauwe** [comment]
That is a possible workaround to have no text :)

Thinking further about this, BablonCpp supports ImGUI that allows you to draw 2D primitives such as lines, rectangles, circles in the background/foreground draw list, as illustrated in the picture below (screenshot was taken from the ImGUI demo samples).

![54287572-2e964b00-45a6-11e9-93ab-e22f09f208be](https://user-images.githubusercontent.com/24841018/160249664-fd28718e-d1ce-4bc4-a2b3-8d919886e470.png)

Maybe the same approach works for text too or you can create a fully transparent ImGUI window with no borders to put your text in.
