### ISSUE TITLE
Please support MSYS2 MINGW64

### ISSUE THREAD

**Issue by ghost** [samdauwe/BabylonCpp#93]

**Comment by samdauwe** [comment]
Hi,

I stopped maintaining this project. Adding MSYS2 support should not be that difficult for this project, so feel free to give it a try. I can merge your changes back, just let me know.

With best regards,
Sam

**Comment by ghost** [comment]
> Hi,
> 
> I stopped maintaining this project. Adding MSYS2 support should not be that difficult for this project, so feel free to give it a try. I can merge your changes back, just let me know.
> 
> With best regards, Sam

Please tell it clear that you stopped maintaining this project on README.md
